//
//  Description.h
//  AppFitness
//
//  Created by Andrei on 27/04/14.
//  Copyright (c) 2014 Licenta. All rights reserved.
//

#import <Foundation/Foundation.h>

#pragma Abdominals
#define AbsbentKneeHipRaise  @"This is a good exercise core muscle development. \n\n Steps:Lie on your back with your arms outstretched to your sides. Bend your kness at a 60 degree angle and hold your feet up just off the floor. \n\n Keeping your back and arms down,raise your hips up and off the floor so that your knees are over your chest. Contract your abs for a moment and then return to the starting position."
#define AbsCrossBodyCrunch  @" This version of the crunch works both the upper and lower portion of the abs.\n\n Steps:Lie on your back and bring your knees up to  a 60 degree angle,keep your feet flat on the floor. Place your hands on either side of your head (over your ears). Curl uo raising your right elbow and your left knee so that they touch over your chest. Return to the starting position and repeat with alternate arms and legs. \n\n Tips:Contract your abs as youtwist during this exercise."
#define AbsCrunches @"This is the most common abdominal exercise and possibly the most often improperly  performed.Here is how to perform it correctly. \n\n Steps:Lie on your back with your feet up on a bench and your knees bent at a 90 degree angle. Place your hands across your chest or on either side of your head(over your ears). \n\n Raise your head , shoulders and chest off the floor and towards your knees, crunching your abs. Hold the position for a moment and then lower to the starting position.\n\n  Tips:Keep your hips straight and your lower back against the floor during this exercise."
#define AbsDeclineCrunch @"Using a decline crunch allows you keep your legs steady and isolate all of the abdominal muscles. \n\n Steps:Lie on a decline bench face up. Place your feet securely under the pads.\n\n  Place your hands either across your chest or on either side of your head (over your ears). Lay fully back and then raise slowly crunching your abs. Pasue for a moment and then return to the starting position.\n\n Tips:Use the full range of movement in this exercise for the optimal results."
#define AbsLegRaise @"Leg raises work your lower abs which are usually hard muscles to target. \n\n Steps:Lie on a flat bench if you have one.If you dont't ,then just lie down on the floor. Keep your hands under your hips to support your back. \n\n Your legs should be hanging off the bench from your knees down.With your feet together and your toes pointed ,raise your legs straight up towards the ceiling.Keep your legs straight but dont't lock your knees. Pause at the strating position in slow controlled manner. \n\n Tips:The range of motion doesn't have to be large for this exercise to be effective."
#define AbsSeatedAbCrunch @"This exercise uses the weight of a cable machine  to assist in a abs crunch.\n\n  Steps:Attach a rope to a high cable pulley. Place a bench in front of cable weight stack. Grasp the rope on over your shoulders and sit with your back towards the stack. \n\nWith your feet firmly on the floor and keeping  your hips steady,flex at the waist bringing your elbows towaards your knees. Return to the starting position.\n\n  Tips:Perform this exercise in a slow controlled manner."
#define AbsSideBend @"This exercise works the obliques ,the muscles on the sides of your abs.\n\n Steps:Stand with your feet shoulder width apart, your knees slightly bent and your abs drawn in. Grasp a dumbbell in one hand and standing upright bend at the waist as far as possible to one side.\n\n Slowly return back up to the staring position.  Switch the dumbbell to your other hand and repeat the exercise. \n\n Tips:Be careful to bend only at your waist and not at the hips or knees."
#define AbsSidePlank @"A simple exercise for core strength and conditioning.  \n\n Steps: Lay on one side of your body with your legs straight and your forearm perpendicular to your body in front of you. Drawing your abs in ,slowly raise yourself up so you are balanced on your feet and your forearm. Hold this position  and slowly return back to the starting position."

#pragma  ArmsBiceps
#define ArmsBicepsAlternateHammerCurl @" This exercise  uses a hammering (up and down) motion to isolate the biceps. \n\n Step:Stand with our feet shoulder width apart ,your knees slightly bent and your abs drawn in. Grasp a dumbbell in each hand so your palms are facing  each other. Extend your arms so they are at the sides of your body. \n\n Keeping your elbows locked lift your left arm in an arc towards your left shoulder. Lower your arm and repeat with your right arm. \n\n Tips:Do not turn your wrists during this exercise."

#define ArmsBicepsCurlBarbell @"This is a basic exercise for the biceps (arms). \n\n  Steps:Stand with your feet shoulder width apart, your knees slightly bent and your abs drawn in. Grasp a barbell with a shoulder width underhand(palms facing up)grip. \n\n Lower your arms fully to above your thighs and bending only your elbows,raise the bar to your upper chest. Pause for a moment and then return to the starting position. \n\n Tips:Do not swing your hips or back during this exercise."
#define ArmsBicepsCurlDumbbell @"This version of a biceps curl uses both arms at the same time. \n\n Steps:Sand with our feet shoulder width apart,your knees slightly bent and your abs drawn in. Grasp a dumbbell in each hand so your palms are facing up. Extend your arms so they are at the sides of your body. \n\n Keeping your elbows locked lift your arms to your chest so that your forearms touches your biceps. In a slow controlled manner lower your arms to the starting position. \n\n Tips:Do not swing your body as you perform  this exercise."
#define ArmsBicepsCurlWithDeadlift @"This is an advanced exercise.This exercise combines a bicep curl with a deadlift .\n\n  Step:Grasp an EZ Crul or barbell with a close underhand(palms facing up ) grip. Standing with your feet shoulder width apart and your knees slightly bent,draw your abs in. Extend your arms so the bar rests in front of your thighs.\n\n Bending at the waist, bring the bar down to just above the floor. As you return to a standing position, bring the bar up and curl your arms bringing your forearms to your biceps. Return the starting position and repeat.\n\n  Tips:Performing this exercise in front of a mirror may help you spot and correct your form."
#define ArmsBicepsConcentrationCurl @"Concentration exercises limit your range of movement to increase the effectiveness of the movement.\n\n  Steps:Sit on the end of a flat bench with your feet flat and your legs spread like a V.Grasp a dumbbell in your hand ,palms facing up. With your elbow pressed against your inner thigh just above your knee, curl the dumbbell up towards your chest. Slowly return to the starting position.Repeat and switch arms.\n\n Tips:Keep all of your body still except the arm you are exercising"
#define ArmsBicepsOverheadCurl @"By using cable this Exercise isolates and defines the biceps (arm) muscles.\n\n Steps:Attach a stirrup handle to each side of a high pulley on a cable machine. Grasp the handles with an under hand grip(palms facing up) and stand with your feet shoulder width apart. Extend your arms fully to each side. \n\n  Keeping your elbows steady curl your wrists towards the sides of your head. Contract your biceps and pause for a moment and then return to the starting position."
#define ArmsBicepsRopeHammerCurl @"Using the rope with the cable machine allows you isolate the biceps with this version of the Hammer Curl.This is a good exercise for beginners. \n\n Steps:Attach a rope to a cable pulley to the bottom of the weight stack. Stand with your feet shoulder width apart,your kness slightly bent and your abs drawn in.Grasp the rope with a close underhand grip (palms facing up).Lower your arms fully to above your thighs and bending only your elbows, raise the rope to your upper chest. Pause for a moment and then return to the starting position. \n\n Tips:Keep your elbows at your side throughout this exercise. Do not swing your hips or back during this exercise. "
#define ArmsTricepsBarbellinclineTricepsExtension @"This version of a triceps extension uses gravity to increase the resistance of the exercise.\n\n  Steps:Grasp a  barbell  with a close grip(4-6 inches apart). Lie on an incline bench and hold the bar over your head. \n\n Lower your arms ina slight arc so your forearms are touching you biceps.Slowly return back to the starting postition with the bar over your head."
#define ArmsTricepsBenchDips @"This exercise is one of the most basic and still one of the best for building the triceps(muscles on the back of the arm).\n\n Steps:Place two benches parallel to each other 3-4 feet appart. Sit one bench and place your feet on the edge of the other bench so that your legs are suspended between the 2 benches. Cross your feet for support. Hold onto the bench with your hands for support and slowly lower body towards the floor by bending your elbows.Pause and then return to starting position.\n\n Tips:Do not go below a 90 degree angle as this can cause on your shoulders. "
#define ArmsTricepsJMPress @"This exercise is named after the inventor, J.M. Blakley. This  is and advanced exercise used by bodybuilders and power lifters to build explosive power in the triceps muscle (back of the arms). \n\n  Steps:Lay on a flat bench with your head just at the end of the bench. Grasp the bar with a medium overhand grip keeping your elbows close to your side ,over your  sternum(mid chest).Lower the bar towards your sternum at a regular pace,then pause for a moment and with a controlled rapid pace, push the bar back to starting position.\n\n Tips:The bar should move in straight line, up and down."
#define ArmsTricepsLyingTricepsPress @"This is another classic exercise for building the triceps.\n\n Steps:Lie ona flat bench with your head at one end. Grasp a EZ or Curl bar with an overhand grip. Raise the bar straight up over your shoulders, keeping your elbows close in. Slowly lower the bar in an arc over your head. Return the bar to the starting position.\n\n Tips:Keep your arms straight throughout this exercise moving only your elbows."
#define  ArmsTricepsOneArmTricepsExtension @"This exercise isolates the triceps muscles individually.\n\n   Steps:Place a cable pulley on the highest setting and adjust a stirrup handle to the pulley. Stand facing the weight stack and grasp the handle with and underhand grip. Keep your back straight ,your abs drawn in and your knees slightly bent.Starting at the top push your arm down until it is straight, feeling the concentration in your tricep.Slowly return to starting position.\n\n Tips:Keep your elbow close to your side while performing this exercise."
#define ArmsTricepsSeatedTricepsPress @"This exercise uses a single dumbbell held between both hands to work the triceps.\n\n   Steps:Sit on a short straight backed bench with your feet planted firmly on the floor.Drawing your abs in and grasp the dumbbell with both hands with a palms up grip and raise the weight over your head,this is your starting position.\n\n Lower the dumbbell in an arc from above your head to behind your back.Slowly return to the starting position."
#define ArmsTricepsStandingOneArmTricepsExtension @"This is a single arm version of a behind the neck triceps exercise. \n\n Steps:Stand with your feet shoulder width apart,your back straight and your abs drawn in.Hold a dumbbell in your right hand with your palms facing up. Raise the dumbbell over your head and slowly lower the dumbbell in an arc behind your head, so that the  dumbbellines up with your spine. \n\n Slowly raise the dumbbell back up to the starting position. Switch arms and repeat. \n\n Tips:Keep your elbows close to your head during the exercise."
#define ArmsTricepsDumbbellKickback @"This along with the Triceps Push Down is one of the most beneficial exercises for the arms.\n\n Steps:Standing along side a flat bench , bend your left knee and place it on the bench.Place your left hand on the bench for support,keeping your back at a 45 degree angle.Hold a dumbbell in your right foot on the floor.Bend your right arm and raise it up to  your shoulder,then with controlled motion kick it back, fully extending your arm.Switch arms and repeat. \n\n Tips:Keep your elbow close to your body during this exercise."
#define ArmsTricepsPushdownVBar @"This exercise is the triceps pushdown uses a V shaped bar. Many people find this version easier on the elbows.\n\n Steps:Stand in front of a cable machine and attach a V bar to a high pulley. Grasp the bar with an overhead(palms facing down)grip. Draw your abs in and keep your back straight. Keeping your elbows at your side push the bar down towards your thighs. Pause for a moment and then return to the starting position.\n\n Tips:You many want to stand one foot in front of the other for a better stance."

#pragma back
#define BackFlyesWithResistanceBands @"Back Flyes will strengthen your upper back and imporeve your posture.\n\n  Steps:Place a resistance band mid-waist high around a post or exercise machine.Keeping your feet together,you abs tight, and your knees slightly  bent, stand far enough beack from the post that there is tension in the band.From there ,bring your arms back in a controlled manner until they are parallel to your sides.Slowly return your arms to the starting position.\n\n Tips:Be careful not to use a band that's so strong you can't use good form."
#define BackHyperextensions @"This exercise not only adds strenght but also flexibility to the back and core muscles.\n\n Steps:Adjust the hyperextension bench so that your ankles are tucked under the footpads and your thighs are flat across the top pad. With your arms folded across your chest and your back straight,slowly bend at the waist towards the floor, keeping your back flat. Slowly return to the starting position. \n\n Tips:Do not arch your back at any time during this exercise."
#define BackRearDeltoidRow @"Rear Deltoid Rows are a simple ,yet effective exercise for targeting your lats and rear deltoids.\n\n Steps:Place your right foot on the floor with you left knee resting on a beanch.Support your body weight with your left arm.With a flat back,pick up the dumbbell in your right hand.\n\n   Leading with your elbow and with your elbow and with your arm close to your chest ,raise your arm.Pause at the top of the exercise then lower in a controlled manner.Switch sides and repeat. \n\n  Tips:Keep your back flat and your head in alignment with your body during this exercise."
#define BackReverseGripBentOverRows @" This exercise is excellent for developing overall back strength.\n\n  Steps:Keeping your knees bent and your back straight ,pick up the barbell.Grasp the bar with a reverse or Underhand grip.Slowly pull the barbell to your abs.Keep your elbows tucked in to your sides.Pause at the exercise then lower the barbell in a controlled manner.\n\n Tips:You must keep your back straight when you do this exercise.If your back starts to round ,just bend your knees a little more to keep it straight. "
#define BackSeatedCableRows @"Cable Seated Rows target the large musclesin your back.\n\n Steps:Sit at a low pulley machine with your feet resting against the footrests and your knees slightly bent.Sit in an upright position ,keeping your abs tight and your back straight. \n\n Lean forward slightly and grasp the pulleys then return to your upright position.Keeping your elbows close to your chest,slowly bring them back.Pause at the top of the contraction and slowly return to the starting position. \n\n Tips:Keep your back upright through the entire exercise."
#define BackTBarRow @"If you have a T-Bar machine, this is a good exercise for building the major muscles of your back. \n\n Steps:Place your feet on either side of a T-Bar Machine.With your knees slightly bent and abs drawn in ,grasp the jandles with a narrow grip. Bend your body at your waist so that your torso is almost parallel to the floor.From this starting position,slowly pull the bar up towards your chest. Pull the bar as high up as you can.Hold the top of this exercise for a moment then lower the handles back to the starting position.\n\n Tips:Keep your elbows close to Your body while doing the T-Bar row."
#define BackVBarPullDown @"This is another exercise for sculpting the lats (muscles of the back).\n\n Steps:Attach a V bar to the pull down pulley of a cable machine. Sitting upright with your abs drawn grasp the bar with an overhand grip,your palms facing in.Pull the bar straight down to your upper chest.Pause for a moment after touching the chest and then slowly return the bar to starting position.\n\n Tips:Keep your back straight during this exercise."

#pragma mark -Chest
#define ChestBarbellInclineBenchPress @"This is a variation of the bench press that targets your upper chest by using an incline bench. It'll help  give your fuller ,more balanced size. \n\n Steps:Set your bench to a 45 degree angle or find a specially designed inclined bench press bench. Lie flat on the bench with your feet firmly on the floor.Grip the bar slightly wider than shoulder-width apart.Lift the bar off the rack and hold it directly above your chest in the starting position. \n\n Lower the bar until it touches your chest, then hold it for a few moments.  Finally, raise the bar up to the starting position. \n\n Tips: Use a slow, controlled motion for the incline bench press. Don''t lock your elbows when you''re in the starting position.The crossover with bands exercise targets your chest and biceps while offering a unique, variable resistance. "
#define ChestBenchPress @"The mighty bench press is a great exercise for building a powerful chest.The bench press is one of the power exercises, known to be very effective for building body mass. Learning how to do a proper bench press is well worth the effort.\n\n Steps: Most gyms have benches specifically designed for the bench press and its variations. Lie flat on one of these benches with your feet firmly on the ground. The bar should be resting on the bench''s rack.Lift the bar off the rack and hold it above your chest in the starting position. \n\n Lower the bar down until it touches your chest. Hold this position briefly and make sure you have complete control of the bar. Now raise the bar up to the starting postion.Return the bar to the rack after you''ve completed your set.\n\n Tips: The width of your grip on the bar will change the focus of the bench press. A medium grip is most common. This is slightly wider than shoulder-width apart. It''s usually marked on the bar.Having a spotter to help you with the bench press is essential. A competitive, motivating spotter is one of the most valuable assets you can find.Choose a weight that is challenging and allows you to maintain proper form. Improper form is less effective and could result in an injury. Use a slow controlled motion and never lock your elbows."
#define ChestButterfly @"The butterfly machine is a simple way to target your chest. This is a machine exercise, so it''s very easy to do.\n\n Steps: Sit on the machine with your back flat. Adjust the height of the seat so that the pads of the machine are at your chest height. Put your forearms against the pads. Push the pads together as you squeeze your chest. Push until the pads meet in the middle. Hold this position for a moment then return to the starting position.\n\n Tips: Focus on using your chest for this exercise. You should be squeezing from the inner part of your chest, not pushing with your biceps or shoulders."
#define ChestCableCrossover @"The cable crossover is a good exercise for targeting your inner chest. It does require that you have 2 cable machines facing each other, but this is a common setup in most gyms.\n\n Steps: Attach handles to the higher pulleys of both cable machines. Stand between the two machines with your legs and waist slightly bent. Grip the handles of the pulleys with your palms facing down and your arms out to your sides.Slowly pull the handles down towards the floor until they touch or cross over in front of you. Hold this position for a few moments then return to the starting position.\n\n Tips: When your arms are in front of you, contract your pectorals for a moment to make this exercise even more effective."
#define ChestDeclineDumbbellBenchPress @"The dumbbell incline bench press targets your lower chest. It incorporates your stability muscles more than the standard incline bench press.\n\n Steps: Lie on a decline bench so that your head is lower than your feet. Grip a pair of dumbbells with an overhand grip, your palms facing towards your feet.\n\n Hold the dumbbells directly above your chest so that their inner edges are touching.Slowly lower the dumbbells all the way until they are inline with the top of your chest. Then, raise them straight up to the starting position. \n\n Tips: The dumbbell bench press puts more focus on your stabilizing muscles. You could alternate between the dumbbell and the barbell versions of the exercise to get the benefits of both exercise types."
#define ChestDumbbellBenchPress @"The dumbbell bench press is a great alternative to the standard bench press. You can do the dumbbell bench press without relying on a spotter. It''s also good to alternate between the standard bench press and the dumbbell bench press so your muscles don''t get too used to either. \n\n Steps: Pick up your dumbbells and hold them at your sides. Then sit on the edge of your flat bench. Sit back as you use your thighs to lush the weights up to their starting position.Start with your arms holding dumbbells about an inch higher than your chest.\n\n  The dumbbells should be in line with the middle of your chest so that your arms are comfortably out to the sides.Slowly push the dumbbells up. Focus on using your chest and triceps to push most of the weight. Stop when your arms are straight and the dumbbells are directly above your chest. Don''t clank the dumbbells together or spin them around when you get to the top.Next, slowly lower the dumbbells. Don''t let gravity do the work. You should be resisting gravity all the way down. The rep ends when the dumbbells are back to 1 inch above your chest. \n\n Tips: Breathe comfortably and deeply. Especially while you''re pushing the dumbbells up"
#define ChestDumbbellInclineBenchPress @"This variation of a bench press is a great workout for your upper chest. \n\n Steps: Start by setting up a bench so that it has a 30 degree incline. Place 2 dumbbells by your feet then sit in the bench.Bring the dumbbells to their starting position just above your chest. Your elbows should be bent so that your forearms are facing directly upwards.Push the dumbbells straight up.\n\n  Focus on using your chest for this exercise. You should feel as if the lifting is coming from your elbows. Raise the dumbbells as high as you can without locking your elbows, then slowly lower them to the starting position." //prea lung
#define ChestDumbbellPullover @"A variation on the standard barbell bent arm pullover, using only a single dumbbell. \n\n Steps: Lie on a flat bench with your head near or over the end of the bench. Hold the dumbbell above your chest by griping the plates of one side. Keep your elbows slightly bent.Lower the dumbbell back behind your head, down towards the floor.\n\n  You should feel the stretch in your chest and triceps. Continue until your arms are next to your head. Then reverse the exercise and return to the starting position.\n\n Tips: Make sure you feel the stretch of the dumbbell bent arm pullover."
#define ChestInclineDumbbellFlyes @"This is a sculpting exercise for the pectoral muscles (Chest). \n\n Steps: Lie on an incline bench set a 45 degree angle with a dumbbell in each hand.Lift the dumbbells over your chest extending your arms fully.Keeping a slight bend in your elbows, lower the dumbbells towards the floor in and arc like motion.Slowly return to starting position.\n\n Tips: Keep your hips and shoulders on the bench at all times during this exercise."
#define ChestSmithMachineBenchPress @"This is the same exercise as a Bench Press but using the Smith Machine allows for greater control of the bar throughout the exercise. \n\n Steps: Place a flat bench in the middle of the Smith Machine, with the bar in line with the middle of your chest.Lying on the bench, grasp the bar at shoulder width apart.Unlatch the bar and slowly lower the bar to your chest.Extend your arms fully and raise the bar to the starting position.\n\n Tips: Keep your back flat on the bench throughout the exercises. The Smith Machine is a good tool for beginners to learn to use free weights safely."

#pragma mark -Shoulders 
#define ShArnoldDumbbellPress @"The Arnold Press is a variation of a standard military press that allows it to also target the rotator cuffs. It targets both your front and side deltoids. \n\n Steps: Sit on a flat bench, feet pointed forward and abs tight. Using an underhanded grip, grasp a dumbbell in each hand with elbows bent and palms facing in slightly below shoulder level. Using a steady controlled motion, raise the dumbbells while rotating your shoulders and turning your thumbs in to face each other.Using a controlled motion, lower the dumbbells in the reverse manner to the starting position.\n\n Tips: Avoid the Arnold Press if you are experiencing shoulder pain. Beginners should try this exercise with light weight to master the correct form. For most people, the rotator cuffs are underused. Keeping the weights light as you master the Arnold Press will help avoid injury."
#define ShBarbellUprightRow @"The barbell upright row is a standard upright row exercise that targets your traps and deltoids. \n\n Steps: Stand up straight with your feet shoulder width apart. Grip the barbell with an overhand grip (palms facing towards your body). Don''t drop your shoulders. Even in this starting position the bar should be inline with the bottom of your hip bone.Next, raise the bar towards your chin. Focus on contracting from your shoulders and traps. Raise the bar to just above your collar bone. \n\n Hold this position for a moment then slowly lower the bar back to its original position.Tips: If possible, perform the barbell upright row using a rack. You''ll be able to rest your barbell on this rack and pick it up from a more comfortable height when you start. This is safer than picking the barbell up from the floor.\n\n Keeping your abs tight will help protect your back during the upright row.Maintain good posture and keep your wrists straight. A shoulder width grip is best. A narrower grip will target the traps more, but it will make you more susceptible to a shoulder injury."
#define ShBentOverLowPulleySideLateral @"The bent over cable lateral raise is a good exercise for targeting your rear deltoids. The cable machine offers a consistent resistance than a dumbbell bent over raise.\n\n Steps: First attach a handle to the cable machine. Stand with your side facing to the cable machine. Bend your knees and your hips to get yourself into the bent over position. Don''t bend your back. From the side you should look like a lighting bold symbol.Grab the cable handle with the arm furthest from the cable machine.\n\n Your arm should be going across the front of your body. Raise your arm across your body and out to the side. Continue until your arm is level with the ground. Hold the top position for a second then lower your arm again and return the the starting position."
#define ShBentOverRearDeltRowWithHeadOnBench @"The advantage of this exercise over a standard rear delt row is that you can use the bench to keep yourself stable and avoid back injuries. \n\n Steps: Stand in front of an incline bench holding a pair of dumbbells. Bend your knees slightly and keep your abs tight. \n\n Slowly bend over until your forehead touches the top of the bench. Your arms should be hanging and your palms facing each other.Slowly raise your arms out to the side. Focus on using the back of your deltoids for this exercise. Raise the dumbbells until your arms are parallel with the floor. Hold this position for a moment, then slowly lower the dumbbells."
#define ShCableSeatedRearLateralRaise @"This is an interesting variation on the standard lateral raise. \n\n Steps: Place a bench between 2 cable machines. Grip the handle of the cable machines so that your arms are crossed behind your back. Grab the left pulley handle with your right hand and visa versa. Sit down on a bench with your feet far forward and your arms crossed under your thighs. Lean forward until your chest is touching or just above your knees.Slowly pull your arms out to the side. \n\n Lead with your elbows and concentrate on using your shoulders to do the lifting. Raise your arms until they are parallel to the ground. Hold this top position for a moment, then lower your arms back to their starting position."
#define ShDumbbellShoulderPress @"The Dumbbell Shoulder press is a variation of the standard military press that puts more focus on the stabilizer muscles. It''s good to alternate between the barbell and dumbbell versions of this exercise. \n\n Steps: Start the dumbbell shoulder press by sitting on a bench with your abs drawn in and a dumbbell in each hand. Your palms should be facing forward and your hands should be at the height of your shoulders. Extend your arms to raise the dumbbells until your arms are straight and the inside edge of each dumbbell is above your head. You can touch the dumbbells together if this is comfortable.Hold this position for a moment, then lower and bend your arms slowly. Continue until your hands are once again at about shoulder level.\n\n Tips: Make sure you don''t lock your elbows in the top position of the shoulder press. Locking your elbows, especially when you''re using heavier weights, can cause very serious injuries.You can also do this exercise on an exercise ball."
#define ShFrontCableRaise @"The Cable Front Raise works your front shoulder muscles to improve all of your arm movement and help with everyday life. And you''ll feel better with sculpted shoulders. \n\n Steps: First attach a handle to the cable machine. Grab the cable handle with an overhand grip. Keep your abs tight. With your arms relatively straight, only a slight bend in your elbows, and your knees slightly bent, raise the arm to shoulder level. Hold briefly then lower in a controlled manner. \n\n Tips: Be sure to hold your abs tight to support your back. Even though it''s tempting, don''t bend back to help you lift. Also, be careful not to lock your elbows."
#define ShMachineShoulderPress @"The shoulder press machine primarily works the deltoids, but it also brings the surrounding muscles into play. Working all the shoulder muscles simultaneously helps to prevent injuries caused by muscle imbalances.\n\n Steps: Sitting upright with your abs locked in, grab the bar with both hands. Using a smooth motion, press the bar upward by extending your arms. Pause briefly at the top then lower your arms in the same controlled manner. \n\n Tips: Adjust the seat so the handles are level with your shoulders as you are sitting upright. Be sure to maintain good posture even though you are seated."
#define ShSeatedBarbellMilitaryPress @" Like the seated shoulder press using a machine, this exercise primarily works the deltoids, but it also brings the surrounding muscles into play. Working all the shoulder muscles simultaneously helps to prevent injuries caused by muscle imbalances.\n\n Steps: Sit on the bench with your toes pointing forward, back straight and your abs tight. Grip the barbell in an overhand grip (palms facing away from your body). Keep your hands about shoulder width apart. The bar should be in line with your chin. Press the barbell upward by extending your arms. Pause briefly at the top then lower the barbell in a slow, controlled manner into its original position.\n\n Tips: You should not do this exercise if you are experiencing any shoulder pain.Be careful not to hyperextend your back. If you can''t do this exercise without leaning back, then use a lighter weight.This exercise can also be done with dumbbells."
#define ShSideLateralRaise @" Dumbbell lateral raises will help build strong shoulders and improve definition.\n\n Steps: Standing with your feet shoulder-width apart and your abs tight, grasp a dumbbell in each hand, palms facing towards your body. Keep a slight bend in your knees as you raise your arms to the side until your palms face the floor. Hold this position briefly then lower slowly.\n\n Tips: Try to feel as if you''re leading with your elbows and keep your wrists lower than your elbows.Resist the temptation to swing the weights. Your shoulders should do the lifting, not momentum."
#pragma mark -Legs 
#define LegsBarbellLunge @" This is a classic leg and lower body exercise with many variations this is the basic version.\n\n Steps: Start by place a barbell across your upper back, use a grip slightly wider than your shoulders.Stand with your feet about 8 inches apart, toes facing forward.Take a step forward (2-3 feet) keeping your abs drawn in and your upper body straight.Slowly lower one knee down as if kneeling while keeping your other knee bent at a 90 degree angle, do not let your knee touch the ground.Lower your body to just above the floor and hold for a moment before returning to the starting position.\n\n Tips: Do not the pressure of your body on your knee during this exercise.The knee you are leaning forward on should not move beyond the toe of this foot."
#define LegsBarbellSquat @"The barbell squat is one of the main power exercises, used for building muscle mass and strength in the quads.\n\n Steps: Unless you''re doing squats with a very low weight, we recommend using a squat rack to help you with this exercise. Start by setting up your desired weight with the bar on the squat rack. Position the bar so that it''s rest on your trapezius, then lift it off the squat rack.Keep your head looking slightly upwards. Now bend your knees and push back your hips. Keep your back straight as your lower your body. \n\n Continue until your quads are parallel with the ground. Hold the lower position for a moment, then raise your body back up again.A rep is finished when you''re standing up straight again. \n\n Tips: Keep your head looking slightly upwards. This will help prevent you from arching your back.Keep your abs tight to take pressure off your back.Before you start using a heavy weight, make sure your back is strong enough to handle the pressure. Perform dead lifts and supermans.If you feel pain in your back after doing squats, stop doing them immediately. After your back has recovered, use a lower weight.Remember to breathe."
#define LegsButtLift @"A great exercise for beginners and experienced alike. Bridges along with Planks are simple yet effective tools for building and maintaining cores strength. \n\n Steps: Lie on your back with your knees bent and your feet flat on the floor.Lift up hips off the floor as you draw your abs in and keep your glutes tight"
#define LegsExtensions @"This exercise is a staple for building strong legs.\n\n  Steps: Adjust the seat so that your knees have fill range of motion and that footpad fits over your legs just above your ankles.Grasp the handles with your hands for support, keeping your hip and back against the bench.Slowly extend your legs until your knees are straight, do not lock your knees.Hold for a moment and then with controlled movements return to the starting position. \n\n Tips: Use controlled movements for this exercise, do not swing the weight up."
#define LegPress @"Along with the Squat this exercise is crucial for building and strengthening the legs. \n\n Steps: Adjust the seat of the machine so that your feet comfortably reach the crosspiece with a slight bend in your knees.To begin press your feet forward at a shoulder width stance and release the safety locks.Slowly lower the weight towards your body, keeping your abs drawn in and your knees moving in the same direction as your feet to a 90 degree angle. \n\n Tips: Do not lock your knees or bounce the weight."
#define LegsOneLeggedCableKickback @"A favorite exercise for anyone looking to firm up their glutes. \n\n Steps: Standing at a cable tower attach an ankle cuff to a low pulley.Facing the weight stack, with a slight bend in your knees and your abs drawn in slowly kick your ankle back in and arc as high as you are able to.Return to starting position and switch ankles."
#define LegsRomanianDeadlift @"This exercise is similar to a regular Deadlift but differs because you keep your legs straight and you bring the bar all the way to the ground at each rep.\n\n  Steps: Place a barbell in front of your feet on the ground.Grasp the barbell with a grip a bit wider than shoulder width apart.Bend your knees slightly, keeping your hips and back straight.Lift the bar straight up concentrating on using your hips as you stand.When you are standing the bar should be resting against your thighs.Lower the bar to the floor with a slight bend in your knees flexing your hips back for stability.\n\n Tips: Use light weight to get used to this exercise.Keep your arms straight throughout the exercise."
#define LegsSeatedCalfRaise @"This is one of the simplest and most effective exercises for the calves. \n\n Steps: Sit at a calf raise machine.Put the balls of your feet on the footpad.Place your thighs under the leg pad above your knees.Unlock the bar and slowly raise your toes up as far as possible.Pause for a moment and then return to the starting position.\n\n  Tips: Practice slow and precise movements with this exercise."
#define LegsSeatedLegCurl @"This is another option to laying leg curls for build the hamstrings (muscles on the back of the thighs).\n\n Steps: Adjust the machine so that the footpad is just above your heels.Sit upright with your abs drawn in and your legs in front of you.Slowly curl your legs back towards you and hold for a moment.With controlled movement return to the starting position.\n\n  Tips: Do not swing the weight or move too quickly though this exercise."
#define LegsStandingLegCurl @"This exercise works the hamstrings, the muscles on the back of the thigh.Steps: Standing at a leg curl machine adjust the rear footpad so it is just above your ankle.Grasp the handles of the machine for support and draw your abs in.Raise your foot up towards your back slowly.Return to the starting position and change legs. \n\n Tips: Keep your back straight throughout this exercise. Do this exercise in a slow controlled movement."
#define LegsTighAbductor @"This exercise targets and works the muscles of the outer thigh. \n\n Steps: Sit on the machine and place your knees against the pads.Draw your abs in and abduct or move your thighs apart against the pads.Slowly return to the starting position and repeat.\n\n Tips: Maintain the same level of resistance throughout this exercise for best results."
#define LegsTighAdductor @" This exercise targets and works the muscles of the inner thigh. \n\n Steps: Sit on the machine and place your knees against the pads.Draw your abs in and adduct or move your thighs apart against the pads bringing theme together.Slowly return to the starting position and repeat. \n\n Tips: Maintain the same level of resistance throughout this exercise for best results."
#pragma mark -Cardio 
#define Cardiobiking @""
#define CardioElliptical @""
#define CardioRecumbentBiking @""
#define CardioRowing @""
#define CardioStepMachine @""
#define CardioTreadmill @""
@protocol Description <NSObject>

@end



